### ISSUE TITLE
Upgrade to Go JOSE v3

### ISSUE THREAD

**Issue by hslatman** [smallstep/crypto#140]
The v2 library of https://github.com/square/go-jose seems to be unmaintained. Development of v3 has moved to https://github.com/go-jose/go-jose. We should consider moving to that.

Found out about the v3 after a user reporting an issue with an AzureKMS key stored with `hsm=true`. This doesn't work, because the `kty` returned by AzureKMS is `EC-HSM`. That's not known by the Go JOSE library; v2 nor v3. Created a new issue for that here: https://github.com/smallstep/crypto/issues/141.

**Comment by maraino** [comment]
Added a PR for supporting *-HSM keys to go-jose@v3 https://github.com/go-jose/go-jose/pull/17
