### ISSUE TITLE
[Bug]: AzureKMS keys with `hsm=true` in the URI don't work

### ISSUE THREAD

**Issue by hslatman** [smallstep/crypto#141]
### Steps to Reproduce

1. Try to initialize a CA using `ca init` using below settings (use `STEPDEBUG=1` for more logs):

```console
--kms-root 'azurekms:name=test-foo333;vault=redacted?hsm=true' \
--kms-intermediate 'azurekms:name=test-bar333;vault=redacted?hsm=true'
```

2. Observe error in `CreateKey`

### Your Environment

N/A

### Expected Behavior

The CA to be initialized with root and intermediate keys stored in AzureKMS with HSM protection level.

### Actual Behavior

The following error logs (reported by a user on Discord):

```console
error unmarshaling key
go.step.sm/crypto/kms/azurekms.convertKey
    /Users/jordan/go/pkg/mod/go.step.sm/crypto@v0.23.1/kms/azurekms/utils.go:95
go.step.sm/crypto/kms/azurekms.(*KeyVault).CreateKey
    /Users/jordan/go/pkg/mod/go.step.sm/crypto@v0.23.1/kms/azurekms/key_vault.go:310
github.com/smallstep/certificates/cas/softcas.(*SoftCAS).createKey
    /Users/jordan/go/pkg/mod/github.com/smallstep/certificates@v0.23.0/cas/softcas/softcas.go:245
github.com/smallstep/certificates/cas/softcas.(*SoftCAS).CreateCertificateAuthority
    /Users/jordan/go/pkg/mod/github.com/smallstep/certificates@v0.23.0/cas/softcas/softcas.go:165
github.com/smallstep/certificates/pki.(*PKI).GenerateRootCertificate
    /Users/jordan/go/pkg/mod/github.com/smallstep/certificates@v0.23.0/pki/pki.go:515
github.com/smallstep/cli/command/ca.initAction
    /Users/jordan/Desktop/step_ca_cgo/step/command/ca/init.go:670
github.com/urfave/cli.HandleAction
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:522
github.com/urfave/cli.Command.Run
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/command.go:173
github.com/urfave/cli.(*App).RunAsSubcommand
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:405
github.com/urfave/cli.Command.startApp
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/command.go:378
github.com/urfave/cli.Command.Run
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/command.go:102
github.com/urfave/cli.(*App).Run
    /Users/jordan/go/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:277
main.main
    /Users/jordan/Desktop/step_ca_cgo/step/cmd/step/main.go:118
runtime.main
    /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/proc.go:250
runtime.goexit
    /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/asm_arm64.s:1172
```

### Additional Context

Answer on Discord:

The code breaks at https://github.com/smallstep/crypto/blob/b126dcff6d81464f1d02dfa6e9fada1a3edabf84/kms/azurekms/utils.go#L93-L96
This is because Azure sends back a JWK with kty set to EC-HSM. The JSON is then unmarshaled into a jose.JSONWebKey (via our wrapped jose package), which doesn't know the EC-HSM type. It might be possible to detect the EC-HSM in convertKey before unmarshaling, and changing it to plain EC. I don't think that affects the rest of its operation, but it's a bit of a hack; worth a quick try though. The proper way would be to explicitly check for EC-HSM and handling that transparently in the calls that involve creating of the key and signer, most probably involving the Go JOSE cryptosigner.

More context can be found on Discord.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
Added a PR to go-jose@v3 https://github.com/go-jose/go-jose/pull/17

**Comment by maraino** [comment]
Fixed by https://github.com/smallstep/crypto/pull/197/commits/5b794ccdc03b33a8338acbdbbb814385a678c7f6

**Comment by hslatman** [comment]
Closing this now as it has been fixed in the library, and will be supported with the new CLI release
