### ISSUE TITLE
Add Azure workload identity support

### ISSUE THREAD

**Issue by nbjohnson** [smallstep/crypto#222]
### What would you like to be added
Azure is in the final stages of adding a new authentication method "WorkloadIdentity" and it would be great to be able to retrieve azure keys from keyvaults using this new auth method.

### Why this is needed
WorkloadIdentity will become the standard auth method for azure kubernetes once it is stable and the existing method of pod managed identity is going away.

Workload Identity has just gone stable with the sdks hopefully soon to follow, the current go sdk identity is v1.2.2 and the workload identity support is coming in v1.3.0 which is currently in beta 5.

https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/CHANGELOG.md

**Comment by maraino** [comment]
@nbjohnson Azure KeyVault is already using azidentity v1.2.2. See https://github.com/smallstep/crypto/blob/878092791d7e5ef8530dfa949cfe3cde61373d77/kms/azurekms/key_vault.go#L199-L209


And from what I can see, as long as we update the dependencies to v1.3.0, once it is ready, `NewWorkloadIdentityCredential()` will be automatically called by `NewDefaultAzureCredential()`, see [here](https://github.com/Azure/azure-sdk-for-go/blob/0ed4f9b44366450c69cc4c7a8de2d1492179bad9/sdk/azidentity/default_azure_credential.go#L82-L87). 

Is there anything that I am missing or any parameter that you would like us to add or remove?

**Comment by nbjohnson** [comment]
Yes I do see, just didn't know if there was any additional configuration required, but if it just slots in and picks up the necessary parameters for workloadidentity, great. Now just have to wait on an official 1.3.0 release

**Comment by nbjohnson** [comment]
@maraino Looks like the official 1.3.0 release for azidentity go sdk was just published

https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fazidentity%2Fv1.3.0

**Comment by maraino** [comment]
@nbjohnson wow, it was published 4h ago, same as your comment. I was watching the releases but didn't check those notifications yet. I'll update this.

**Comment by nbjohnson** [comment]
@maraino Thanks for getting that in so quickly, looking forward to having workload identify support in step-ca certificates

**Comment by maraino** [comment]
@nbjohnson I've already updated the dependency in step-ca, and I think we will be releasing a new version soon.
