### ISSUE TITLE
Add support for ASN.1 BOOLEAN type

### ISSUE THREAD

**Issue by 4x0v7** [smallstep/crypto#340]
### What would you like to be added

As the title suggests, it would be nice to be able to do `asn1Enc "bool:false"` `asn1Enc "bool:true"`

### Why this is needed

Encoding a BOOLEAN value is a useful primitive to have, to add to strings and numbers

**Comment by maraino** [comment]
@4x0v7: Thanks for reporting this. I've created a PR to add support for it.

**Comment by 4x0v7** [comment]
Awesome! I found in the meantime this can be done with `asn1Enc "raw:AQEA"` for a false and `asn1Enc "raw:AQH/"` for true
