### ISSUE TITLE
Can't go get from go.step.sm/crypto, revoked certificate

### ISSUE THREAD

**Issue by Zenithar** [smallstep/crypto#35]
Hello,

It looks like your certificate used to serve `go.step.cm/crypto` has been revoked.

Regards,

**Comment by hslatman** [comment]
@Zenithar: thank you for reporting this. It seems we're hit by the Let's Encrypt issue of last week: 

```[go.step.sm]: The certificate retrieved from your web server has serial 04fa7835c8b2c3fa9ed401788641ae9e60a6 and was found in our affected data set. Please renew your certificate as soon as possible. Help is available at https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449```

We'll take a look!

**Comment by hslatman** [comment]
@Zenithar: it should now be fixed.

Again, thanks for your report. I did see logs coming in with failed TLS connections!
